apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-s3
  namespace: cms
  labels:
    app: nest-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-s3
  template:
    metadata:
      labels:
        app: nest-s3
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: nest-s3
          image: nest-s3:latest
          imagePullPolicy: Never 
          ports:
            - containerPort: 3000
          env:
            # --- MinIO Settings ---
            - name: MINIO_ENDPOINT
              value: "minio"
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_ACCESS_KEY
              value: "admin"
            - name: MINIO_SECRET_KEY
              value: "admin123"
            - name: MINIO_BUCKET
              value: "uploads"
            - name: MINIO_PUBLIC_URL
              value: "http://minio:9000"
            
            # --- Kafka Settings ---
            - name: KAFKA_BROKER
              value: "kafka-1768077348-headless:9092"
            - name: KAFKA_TOPIC
              value: "files.uploaded"
            
            # --- App Settings ---
            - name: PORT
              value: "3000"
            
            # --- JWT Settings ---
            - name: JWT_SECRET
              value: "4ba5b968796f41d8de85d6063fe4929d2cb649594090b9d778e54680ec273341"
            - name: JWT_ISSUER
              value: "cms"
            - name: JWT_AUDIENCE
              value: "account"
            - name: JWT_EXPIRY_MINUTES
              value: "60"

---
apiVersion: v1
kind: Service
metadata:
  name: nest-s3
  namespace: cms
spec:
  type: ClusterIP
  selector:
    app: nest-s3
  ports:
    - port: 80
      targetPort: 3000
