name: CI/CD - CMS User Management

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env from example
        run: cp dotenv .env
        
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Unit Tests
        run: npm run test

      # - name: E2E Tests
      #   env:
      #     MINIO_ENDPOINT: 57.129.78.173
      #     MINIO_PORT: 31544
      #   run: npm run test:e2e

      - name: Calculate Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            -t nest-s3:${{ env.IMAGE_TAG }} \
            -t nest-s3:latest \
            -f Dockerfile \
            .

      - name: Import Docker Image
        run: |
           docker save nest-s3:${{ env.IMAGE_TAG }} | sudo ctr -n k8s.io images import -

      - name: Apply Kubernetes manifests
        run: |
          envsubst < kubernetes/deploy.yaml | kubectl apply -f -
